CREATE TABLE intake_limits (
  key text PRIMARY KEY,
  count integer NOT NULL,
  expires integer NOT NULL
);
CREATE INDEX intake_limits_expiry ON intake_limits (expires);

CREATE TABLE intake_leads (
  id text PRIMARY KEY,
  hash text NOT NULL,
  payload text NOT NULL,
  status text NOT NULL,
  cursor integer NOT NULL DEFAULT 0,
  updated integer NOT NULL,
  expires integer NOT NULL
);
CREATE INDEX intake_leads_expiry ON intake_leads (expires);

CREATE TABLE intake_receipts (
  number integer GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
  lead_id text NOT NULL UNIQUE,
  created integer NOT NULL
);
